[project]
name = "python"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.121.1",
    "loguru>=0.7.3",
    "numpy>=2.3.4",
    "openai>=2.7.2",
    "transformers>=4.47.0",
    "torch==2.5.1",
    "uvicorn>=0.38.0",
]
